### ISSUE TITLE
this is work for taking orders but its not change the order status after taking the payment .

### ISSUE THREAD

**Issue by MdTayouburRahman** [2Checkout/woocommerce#12] opened 2020-12-28 00:41 UTC
i sell a digital downloadable product (stock design ) which made by me. and it needs the order mark as complete instantly after a successful Cart purchase. then my customer can download their design file instantly. but now this plugin only accepts the payment but not change the order status . this is very annoying to approve manually every order! Are there any solutions for me?

**Comment by craigchristenson** [comment] 2020-12-28 12:18
I was not able to replicate this issue. The order status should be changing from pending to processing immediately after the order is placed. It could be caused by a misconfiguration or callback issue on your store. Can you confirm which interface you are using (2PayJS, Inline, Convert Plus) and can you confirm that the order status is remaining in 'pending'?

**Comment by MdTayouburRahman** [comment] 2020-12-28 15:55
i face this issue with 2Checkout Convert Plus Payment Gateway.  and i confirm that the order Status is remaining the same and it happened again today. my client hit me on Whatsapp and saying he cant download his files after his purchase. here is my store plugging setup. please check the image 
![2020-12-28_215241](https://user-images.githubusercontent.com/57786253/103226782-0b918280-4957-11eb-83be-84ef1e8d69e5.jpg)

**Comment by craigchristenson** [comment] 2021-01-09 04:33
Thank you for reporting this issue. This has been resolved in the latest release 1.2.0. Please make sure that you setup your IPN URL again after installing as it has changed in version 1.2.0.

**Closed by craigchristenson** 2021-01-09 04:33 UTC
